### ISSUE TITLE
Passing custom waveforms for latency test

### ISSUE THREAD

**Issue by MerinS** [gkasten/drrickorang#17]
From what I could understand, this code passes a sine tone of 719 Hz frequency  through the loopback cable and measure the latency through the loop. Is it possible to replace the sine by any other waveform in the code and pass it though, for a latency test?

**Comment by gkasten** [comment]
It should be possible but ...  We use a sine wave because it makes it easier to do glitch detection. You can pass the sine wave through an FFT and it should have a single peak frequency.  When there is a glitch, it gets smeared all over the spectrum.   So if you could figure out another way to do glitch detection, it should be fine.   What kind of waveform were you thinking of?

**Comment by gkasten** [comment]
p.s. the team I work with is planning on having an audio-related hack day in the SF Bay Area near end of October. If you want some early information please send a note to gkasten at android dot com, thanks. Otherwise there will be a public announcement later when it is finalized.

**Comment by MerinS** [comment]
<Sorry about the delay in replying back,got busy with a few things>A brief context- the device I work on uses the audio path for communication. So I am trying to use the pathway provided by this app to assess the behaviour of the PCM waveforms I send through.The plan is to send out PCM waveforms. I have [attached an image](https://postimg.org/image/rt1l3nk4n/) of the kind of data passed.
Also, I shall send out a mail to get info on the hack.

**Comment by MerinS** [comment]
I realised that since there is a capacitor in series,  passing something encoded in manchester(given how it has excessive DC in and capacitor tends to smoothen it)might not be a great idea. However I will keep working on it. Will update when I have something to share.
